### ISSUE TITLE
Please make a specification, roadmap or to-do list.

### ISSUE THREAD

**Issue by mardab** [nickpascucci/fr4#1]
I like this idea, I'd join in and aid in my free time, but I don't quite see which way you'd like to go. It would be nice to see what has to be done ahead of time, so please include some documentation for that.

**Comment by nickpascucci** [comment]
Hi @mardab; I'm glad you find this interesting. I built this as a personal project. I've made the code available for others to use, but that is as far as I'm going to take it. Ultimately, I'm not interested in running an open source project or managing outside contributors. If you want to adapt FR4 for your own use case you are welcome to do so within the guidelines of the GPL3 license, and I'd be curious to see where you take it!
